apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
    app.kubernetes.io/component: sonarqube-data-pvc
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/part-of: sonarqube
  name: sonarqube-data
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
